export default string = {
  appName: "AgrHub Camera",
  welcome: 'Welcome',
  name: 'Name',
  email: 'Email',
  phone: 'Phone',
  password: 'Password',
  confirmPassword: 'Confirm password',
  forgotPassword: 'Forgot password',
  tandc: "I have read, understand and agree to the Term of Use and Privacy Policy",
  login: "Login",
  signUp: 'Sign up',
  register: "New to",
  camera: "camera",
  cameras: "cameras",
  emailIncorrect: "Your email is not correct",
  passwordIncorrect: "Your password must be bigger 6 charactor",
  loginFail: "Your email or password is not correct, please try again!",
  profileManagerment: "Profile Managerment",
  notificationCenter: "Notification Center",
  feedback: "FAQ & Feedback",
  About: "About",
  Settings: "Settings",
  logout: "Logout",
  scanQRCode: "Scan QR-Code",
  scanQRCodeMessage: "Scan the QR Code located at your devices to intergrate with out system",
  next: "Next",
  cameraMissingPermissionTitle: "Permission to use camera",
  cameraMissingPermissionMessage: "We need your permission to use your camera phone",
  scan: "Scan",
  processing: "Processing",
  selectCameras: "Select Cameras",
  signUpNameError: "Your name should not be null or blank",
  signUpEmailError: "Your email isn't correct",
  signUpPhoneError: "Your phone number should not be null or blank",
  signUpPasswordError: "Your password should not shorter than 6 charactors",
  signUpRePasswordError: "Your confirm password isn't match with your password",
  signUpAgreePolicyError: "Please check that you have agreed to our Term of Use and Privacy Policy",
  signUpError: "We wasn't able to sign up with your information, please check the inputs and try again",
  signUpSuccessTitle: "Confirmation email sent",
  signUpSuccessMessage: "Please check your email and confirm your email address"
}