# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'AgrHubCamera' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for AgrHubCamera

pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga/yoga.podspec'
pod 'React', path: '../node_modules/react-native'
pod 'react-native-rtmpview', :path => '../node_modules/react-native-rtmpview'

  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end
